name: Deploy Dev

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/k8s-dash:${{ github.sha }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t $IMAGE_TAG .
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push Docker image
      run: docker push $IMAGE_TAG

    - name: Print the image tag
      run: echo "Docker image tag is $IMAGE_TAG"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: mohamadalsalty/github-actions-cd
        token: ${{ secrets.TARGET_REPO_PAT }}        

    - name: Update values.yaml
      run: |
        sed -i 's/tag: ".*"/tag: "${{ github.sha }}"/g' src/apps/golang-k8s-api/dev/values.yaml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/apps/golang-k8s-api/dev/values.yaml
        git commit -m "Update tag to ${{ github.sha }}"
        git push      