name: Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get repository name
      id: repo_name
      run: echo "::set-output name=name::$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"

    - name: Build Docker image
      id: docker_build
      env:
        IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo_name.outputs.name }}:${{ github.sha }}
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push -t $IMAGE_TAG .
        echo "::set-env name=IMAGE_TAG::$IMAGE_TAG"

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo_name.outputs.name }}:${{ github.sha }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo_name.outputs.name }}:${{ github.sha }}

    - name: Print the image tag
      run: echo "Docker image tag is ${{ env.IMAGE_TAG }}"
