name: Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE: ${{ secrets.DOCKER_USERNAME }}/k8s-dash

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64 -t $IMAGE:$(date +%s) .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE:$(date +%s) }}

    - name: Push Docker image
      run: docker push $IMAGE:$(date +%s)

    - name: Print the image tag
      run: echo "Docker image tag is $IMAGE:$(date +%s)"
