name: Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get repository name
      id: repo_name
      run: echo "::set-output name=name::$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push -t $IMAGE_TAG .
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: $IMAGE_TAG

    - name: Push Docker image
      run: docker push $IMAGE_TAG

    - name: Print the image tag
      run: echo "Docker image tag is $IMAGE_TAG"
