name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/k8s-dash:${{ github.sha }}

    steps:
    - uses: actions/checkout@v4
    - name: Scan files with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ github.workspace }}


    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t $IMAGE_TAG .
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE_TAG }}
